<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Thu, 02 May 2024 23:10:24 +0000
 */
$conf['title'] = 'Bitnami DokuWiki';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['userewrite'] = 1; // URL rewriting is handled by the webserver
