# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Thu, 02 May 2024 23:10:24 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

user:$2y$10$27C9IHhCfuC71p1dximRZeudWRckfuKcJy0coRIoC6vLgDOw.RL2i:FirstName LastName:user@example.com:admin,user
